"""Generate C++ headers with constant tables extracted from carpet.exe's relocated image.

Spec files: src/mcengine/tables/*.tables, one table per line:

    name  ctype  addr_hex  count   [# comment]

ctype is one of u8 i8 u16 i16 u32 i32. The output is src/mcengine/gen/<stem>_tables.h with
`inline const <type> name[count] = {...};` for every line (C++17 inline variables).

Usage:  python tools/port/gen_exe_tables.py            (regenerate all)
        python tools/port/gen_exe_tables.py terrain    (only tables/terrain.tables)

Run from anywhere; paths are resolved relative to this file. The image is cached by
tools/analysis/img.py in extracted/exe/carpet_flat.bin.
"""
import pathlib, struct, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "analysis"))
import img  # noqa: E402

CTYPES = {
    "u8": ("uint8_t", 1, "<B"), "i8": ("int8_t", 1, "<b"),
    "u16": ("uint16_t", 2, "<H"), "i16": ("int16_t", 2, "<h"),
    "u32": ("uint32_t", 4, "<I"), "i32": ("int32_t", 4, "<i"),
}

def gen(spec: pathlib.Path, out_dir: pathlib.Path):
    lines = ["// Generated by tools/port/gen_exe_tables.py from carpet.exe - do not edit.",
             f"// Source spec: src/mcengine/tables/{spec.name}", "#pragma once", "#include <cstdint>", ""]
    for raw in spec.read_text().splitlines():
        code, _, comment = raw.partition("#")
        parts = code.split()
        if not parts:
            continue
        name, ctype, addr, count = parts[0], parts[1], int(parts[2], 16), int(parts[3], 0)
        cname, size, fmt = CTYPES[ctype]
        vals = [struct.unpack_from(fmt, img.IMG, addr - img.BASE + i * size)[0] for i in range(count)]
        if comment.strip():
            lines.append(f"// {comment.strip()}")
        lines.append(f"// {count} x {ctype} at 0x{addr:06x}")
        lines.append(f"inline const {cname} {name}[{count}] = {{")
        per = 16 if size <= 2 else 8
        for i in range(0, count, per):
            lines.append("    " + ", ".join(str(v) for v in vals[i:i + per]) + ",")
        lines.append("};")
        lines.append("")
    out = out_dir / f"{spec.stem}_tables.h"
    data = "\n".join(lines).encode("utf-8")
    if not out.exists() or out.read_bytes() != data:     # untouched when unchanged (no needless rebuilds)
        out.write_bytes(data)
    print(f"wrote {out} ({len(lines)} lines)")

def main():
    spec_dir = ROOT / "src" / "mcengine" / "tables"
    args = sys.argv[1:]
    out_dir = ROOT / "src" / "mcengine" / "gen"
    if "--out" in args:                                  # CMake: python gen_exe_tables.py --out <build>/gen
        i = args.index("--out"); out_dir = pathlib.Path(args[i + 1]); del args[i:i + 2]
    out_dir.mkdir(parents=True, exist_ok=True)
    only = args
    for spec in sorted(spec_dir.glob("*.tables")):
        if only and spec.stem not in only:
            continue
        gen(spec, out_dir)

if __name__ == "__main__":
    main()
