"""Generate src/mcengine/gen/dispatch_tables.h from the Thing class tables of carpet.exe.

The class table at 0x943da (stride 0x12) points at two record arrays per class:
Table A (update handlers, indexed by Thing.state) and Table B (constructors, indexed by Thing.type).
Records are 14 bytes: {u32 parent = 0x943cc, u16 index, u32 handler, u32 enabled}.

The port keeps the records (index, original handler address, enabled flag, name) and binds C++
functions to them by original handler address at run time (thing_register_update/_create).

Usage: python tools/port/gen_dispatch.py
"""
import csv, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "analysis"))
import img  # noqa: E402

CLASS_TABLE = 0x943da
PARENT = 0x943cc
NUM_CLASSES = 14

def records(t):
    out = []
    while t and img.u32(t + len(out) * 14) == PARENT and len(out) < 256:
        a = t + len(out) * 14
        out.append((img.u16(a + 4), img.u32(a + 6), img.u32(a + 10)))
    return out

def main():
    names = {int(r["address"], 16): r["name"]
             for r in csv.DictReader(open(ROOT / "ghidra" / "export" / "carpet_functions.csv"))}
    lines = ["// Generated by tools/port/gen_dispatch.py from carpet.exe - do not edit.",
             "// Thing class tables (0x943da): Table A = update handlers by state, Table B = constructors by type.",
             "#pragma once", "#include <cstdint>", "",
             "struct DispatchRec {",
             "    int16_t     index;    // must equal the requested state / type",
             "    uint32_t    handler;  // original code address (0 = none)",
             "    uint32_t    enabled;",
             "    const char *name;     // name in ghidra/names (diagnostics only)",
             "};",
             "struct DispatchClass { const DispatchRec *a; int a_count; const DispatchRec *b; int b_count; };",
             ""]
    cls_rows = []
    max_a = max_b = 0
    for c in range(NUM_CLASSES):
        r = CLASS_TABLE + c * 0x12
        row = []
        for tag, t in (("a", img.u32(r)), ("b", img.u32(r + 4))):
            recs = records(t)
            if tag == "a": max_a = max(max_a, len(recs))
            else: max_b = max(max_b, len(recs))
            if not recs:
                row.append(("nullptr", 0))
                continue
            arr = f"g_dispatch_{tag}_cls{c}"
            lines.append(f"// class {c} table {tag.upper()} at 0x{t:06x}, {len(recs)} records")
            lines.append(f"inline const DispatchRec {arr}[{len(recs)}] = {{")
            for i, (idx, h, en) in enumerate(recs):
                nm = names.get(h, "" if h == 0 else f"FUN_{h:08x}")
                lines.append(f'    {{{idx}, 0x{h:05x}, {en}, "{nm}"}},  // {i}')
            lines.append("};")
            row.append((arr, len(recs)))
        cls_rows.append(row)
    lines.append("")
    lines.append(f"constexpr int MC_NUM_CLASSES = {NUM_CLASSES};")
    lines.append(f"constexpr int MC_MAX_TABLE_A = {max_a};")
    lines.append(f"constexpr int MC_MAX_TABLE_B = {max_b};")
    lines.append(f"inline const DispatchClass g_dispatch_classes[{NUM_CLASSES}] = {{")
    for c, row in enumerate(cls_rows):
        lines.append(f"    {{{row[0][0]}, {row[0][1]}, {row[1][0]}, {row[1][1]}}},  // class {c}")
    lines.append("};")
    lines.append("")
    out_dir = ROOT / "src" / "mcengine" / "gen"
    if "--out" in sys.argv:                              # CMake: python gen_dispatch.py --out <build>/gen
        out_dir = pathlib.Path(sys.argv[sys.argv.index("--out") + 1])
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "dispatch_tables.h"
    data = "\n".join(lines).encode("utf-8")
    if not out.exists() or out.read_bytes() != data:
        out.write_bytes(data)
    print(f"wrote {out} ({len(lines)} lines, max A {max_a}, max B {max_b})")

if __name__ == "__main__":
    main()
